#!/usr/bin/env python3
"""Build the P215 paper/export appendix index for the P214 evidence bundle.

P215 is documentation/index integration only. It reads the existing P214
evidence-only release bundle and writes a compact paper/export index that is
easy to cite during review. It creates no labels, performs no training,
downloads nothing, and does not touch raw data.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INPUT_JSON = ROOT / "paper/evidence/evidence_only_release_bundle_p214.json"
OUTPUT_MD = ROOT / "paper/export/evidence_only_appendix_index_p215.md"

REQUIRED_STATUS = "READY_NO_LABEL_EVIDENCE_ONLY"


def load_bundle(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def short_sha(value: Any) -> str:
    text = "" if value is None else str(value)
    return text[:12]


def artifact_link(path: str) -> str:
    full_path = ROOT / path
    if not full_path.exists():
        return f"`{path}`"
    href = os.path.relpath(full_path, OUTPUT_MD.parent)
    return f"[`{path}`]({href})"


def build_markdown(bundle: dict[str, Any]) -> str:
    bundle_status = bundle.get("bundle_status")
    verification = bundle.get("verification", {})
    schema_scan = bundle.get("schema_scan", {})
    p195 = verification.get("p195", {})
    admit = p195.get("human_admit_label", {})
    same_object = p195.get("human_same_object_label", {})

    manifest = list(bundle.get("manifest", []))
    if bundle_status != REQUIRED_STATUS:
        raise SystemExit(f"P214 bundle status is {bundle_status!r}, expected {REQUIRED_STATUS!r}")
    if p195.get("status") != "BLOCKED" or not p195.get("labels_blank"):
        raise SystemExit("P195 label gate is not blocked with blank labels")

    lines = [
        "# P215 Evidence-Only Appendix Index",
        "",
        f"**Integration target:** `paper/export` appendix/review index for P214.",
        f"**P214 bundle status:** `{bundle_status}`.",
        "**Evidence governance:** ready for evidence-only review.",
        "**P195 learned admission control:** `BLOCKED`.",
        "",
        "## Claim Boundary",
        "",
        "Evidence-only governance is ready. P195 learned admission control remains BLOCKED.",
        f"No independent human labels exist: `human_admit_label` has {admit.get('blank')} blank / {admit.get('valid')} valid / {admit.get('total')} total, and `human_same_object_label` has {same_object.get('blank')} blank / {same_object.get('valid')} valid / {same_object.get('total')} total.",
        "No admission or same-object labels were generated by P206-P215. Semantic/category evidence is reviewer/audit evidence only and must not be treated as admission ground truth, same-object ground truth, or training supervision.",
        "",
        "P215 does not create labels, infer labels, train models, download data, modify raw data, or change scientific claims.",
        "",
        "## Primary Citation Targets",
        "",
        "| Status | Path | Claim boundary |",
        "|---|---|---|",
        f"| `{bundle_status}` | {artifact_link('paper/export/evidence_only_release_bundle_p214.md')} | Reviewer-facing P214 evidence-only release bundle. |",
        f"| `{bundle_status}` | {artifact_link('paper/evidence/evidence_only_release_bundle_p214.json')} | Machine-readable P214 governance bundle. |",
        f"| `{bundle_status}` | {artifact_link('paper/evidence/evidence_only_release_bundle_p214.csv')} | Compact artifact manifest; artifact-level metadata only. |",
        "",
        "## P206-P214 Appendix Trail",
        "",
        "| Phase | Artifact role | Status | Path | SHA-256 | Claim boundary |",
        "|---|---|---|---|---|---|",
    ]

    for row in manifest:
        lines.append(
            "| {phase} | `{role}` | `{status}` | {path} | `{sha}` | {boundary} |".format(
                phase=md_escape(row.get("phase")),
                role=md_escape(row.get("artifact_role")),
                status=md_escape(row.get("status")),
                path=artifact_link(str(row.get("path", ""))),
                sha=short_sha(row.get("sha256")),
                boundary=md_escape(row.get("claim_boundary")),
            )
        )

    checks = verification.get("checks", {})
    lines.extend(
        [
            "",
            "## Verification Snapshot",
            "",
            f"- P195 remains BLOCKED with blank human labels: `{'PASS' if checks.get('p195_blocked') else 'FAIL'}`.",
            f"- P214 bundle remains READY_NO_LABEL_EVIDENCE_ONLY: `{'PASS' if bundle_status == REQUIRED_STATUS else 'FAIL'}`.",
            f"- Human labels remain blank: `{'PASS' if checks.get('human_labels_remain_blank') else 'FAIL'}`.",
            f"- Generated P214 output schema has no prohibited row-level decision/proxy columns: `{schema_scan.get('status')}`.",
            f"- Overall P214 verification: `{verification.get('status')}`.",
            "",
            "## P216 Recommendation",
            "",
            "Keep the next phase on the no-label governance boundary unless independent human admission and same-object labels are collected. A productive P216 is either final paper-reference cleanup around this appendix index, or a separate label-collection/import gate that preserves semantic/category evidence as audit evidence only.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    bundle = load_bundle(INPUT_JSON)
    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text(build_markdown(bundle), encoding="utf-8")


if __name__ == "__main__":
    main()
