#!/usr/bin/env python3
"""
Execute a protocol-driven plan in dry-run or shell mode.

Current scope:
- read a plan generated by run_protocol_plan.py
- print each item in order
- optionally execute shell commands one by one
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--plan', type=Path, required=True)
    p.add_argument('--execute', action='store_true', help='actually execute commands')
    p.add_argument('--limit-items', type=int, default=0)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    plan = json.loads(args.plan.read_text(encoding='utf-8'))
    items = plan.get('items', [])
    if args.limit_items > 0:
        items = items[:args.limit_items]

    summary = {
        'protocol_id': plan.get('protocol_id'),
        'revisit_type': plan.get('revisit_type'),
        'num_items': len(items),
        'mode': 'execute' if args.execute else 'dry_run',
    }
    print(json.dumps(summary, indent=2, ensure_ascii=False))

    for idx, item in enumerate(items, start=1):
        print(f"\n[{idx}/{len(items)}] {item['session_date']} {item['sequence']} frame={item['frame_index']}")
        print(item['command'])
        if args.execute:
            subprocess.run(item['command'], shell=True, check=True)


if __name__ == '__main__':
    main()
